primev/mev-commit

contracts-abi/config/testnet.go

Contract addresses were changed again, and the ones in testnet.go are no longer working

fix: contract addresses

---

contracts/contracts/BlockTracker.sol

Deleted this checker because if the builder is not in the map, the oracle will not record the block.

fix: deleted address checker

---

infrastructure/nomad/playbooks/templates/jobs/mev-commit-oracle.nomad.j2

Fixes a duplicate oracle db resource block occurring in the `stressnet` profile.

fix: oracle db duplicate resources block

---

contracts-abi/abi/BidderRegistry.abi
contracts-abi/abi/BlockTracker.abi
contracts-abi/abi/L1Gateway.abi
contracts-abi/abi/Oracle.abi
contracts-abi/abi/PreConfCommitmentStore.abi
contracts-abi/abi/ProviderRegistry.abi
contracts-abi/abi/SettlementGateway.abi
contracts-abi/clients/BidderRegistry/BidderRegistry.go
contracts-abi/clients/BlockTracker/BlockTracker.go
contracts-abi/clients/L1Gateway/L1Gateway.go
contracts-abi/clients/Oracle/Oracle.go
contracts-abi/clients/PreConfCommitmentStore/PreConfCommitmentStore.go
contracts-abi/clients/ProviderRegistry/ProviderRegistry.go
contracts-abi/clients/SettlementGateway/SettlementGateway.go
contracts-abi/config/testnet.go
contracts/contracts/BidderRegistry.sol
contracts/contracts/BlockTracker.sol
contracts/contracts/Oracle.sol
contracts/contracts/PreConfCommitmentStore.sol
contracts/contracts/ProviderRegistry.sol
contracts/contracts/Whitelist.sol
contracts/contracts/standard-bridge/Gateway.sol

To actually be upgradable under a UUPS proxy, implementation contracts must inherit `UUPSProxy` and implement `_authorizeUpgrade`. I previously added this to validator registry, but missed core contracts. See https://docs.openzeppelin.com/contracts/4.x/api/proxy#UUPSUpgradeable-_authorizeUpgrade-address-

fix: core contracts now inherit from UUPSUpgradeable

---

contracts/foundry.toml
contracts/scripts/DeployScripts.s.sol
contracts/scripts/DeployStandardBridge.s.sol

Previously bugs like https://github.com/primev/mev-commit/pull/173 would not be caught by ci, because forge thinks scripts reside in the `script` directory by default. Our script directory is actually `scripts` as addressed in this PR. Now `forge test`, `forge build` etc. will fail as expected when one of the solidity scripts doesn't build.

fix: forge build now specifies correct script directory 

---

infrastructure/nomad/playbooks/variables/profiles.yml
oracle/pkg/l1Listener/l1Listener.go
oracle/pkg/l1Listener/l1Listener_test.go
oracle/pkg/node/node.go
oracle/pkg/updater/metrics.go
oracle/pkg/updater/updater.go
oracle/pkg/updater/updater_test.go
p2p/pkg/node/node.go
x/contracts/txmonitor/eth_helper.go

Preconfirmations can trivially be satisfied by most block builders by placing the transactions at the bottom of the block. This is known as an inclusion preconfirmation. However, most preconfirmations are meant for contested state, like doing cex-dex arbitrage to bring the price an on-chain DEX or AMM into parity with the external world. In such cases, it's important to ensure the provider doesn't simply **_include_** the preconfirmation, but also ensures its successful execution.
We alter the data stored in our LRU cache to also keep track of the status of the transaction (success v.s failure). We subsequently continue our preconfirmation validation as normal, with the additional check of successful execution before the disbursement of rewards.
This is not a required check, as builders …

feat: adds execution enforcement to preconfirmations

---

contracts-abi/abi/PreConfCommitmentStore.abi
contracts-abi/clients/PreConfCommitmentStore/PreConfCommitmentStore.go
contracts/contracts/BidderRegistry.sol
contracts/contracts/PreConfCommitmentStore.sol
contracts/contracts/ProviderRegistry.sol
contracts/contracts/interfaces/IPreConfCommitmentStore.sol
contracts/test/PreConfirmationConfTest.sol

Updated solidity structs, so they will take less storage.
Before (original struct): 
```
struct PreConfCommitment {
bool isUsed;                     // 1 byte
address bidder;                  // 20 bytes
address commiter;                // 20 bytes
uint256 bid;                     // 32 bytes
uint64 blockNumber;              // 8 bytes
bytes32 bidHash;                 // 32 bytes
uint64 decayStartTimeStamp;      // 8 bytes
uint64 decayEndTimeStamp;        // 8 bytes
string txnHash;                  // dynamic
string revertingTxHashes;        // dynamic
bytes32 commitmentHash;          // 32 bytes
bytes bidSignature;              // dynamic
bytes commitmentSignature;       // dynamic
uint64 dispatchTimestamp;        // 8 bytes
bytes sharedSecretKey;           // dynamic
}
```
1. Slot 1: …

chore: updated structs

---

contracts-abi/abi/BlockTracker.abi
contracts-abi/abi/Oracle.abi
contracts-abi/clients/BlockTracker/BlockTracker.go
contracts-abi/clients/Oracle/Oracle.go
contracts/contracts/BlockTracker.sol
contracts/contracts/Oracle.sol
contracts/entrypoint.sh
contracts/scripts/DeployScripts.s.sol
contracts/test/BidderRegistryTest.sol
contracts/test/OracleTest.sol
contracts/test/PreConfirmationConfTest.sol
contracts/test/ProviderRegistryTest.sol
infrastructure/nomad/playbooks/templates/jobs/contracts-deployer.nomad.j2

Closes https://github.com/primev/mev-commit/issues/109. Devnet tested in https://github.com/primev/mev-commit/actions/runs/9980618720

fix: separate oracle and owner accounts in contracts

---

contracts/contracts/validator-registry/avs/MevCommitAVS.sol
contracts/contracts/validator-registry/avs/README.md
contracts/test/validator-registry/avs/MevCommitAVSTest.sol

Adds docs and test to clarify to auditors the correct behavior of:
- `registerValidatorsByPodOwners` being used in conjunction with `isValidatorOptedIn`
- `requestValidatorsDeregistration` and `deregisterValidators` being called by a delegated operator
This PR does not modify contract behavior

docs: clarify MevCommitAVS behavior w/ associated tests

---

pull_request_template.md

Added PR template. Benefits of having it:
* Consistency: all PRs follows the same format, making them easier to review
* Efficiency: guides contributors what to include, speeding up the PR creation
* Thoroughness: Prompts for essential details like changes, testing, and impact, ensuring nothing is missed
* Transparency: Encourages clear communication of changes, improving team transparency

feat: added pr template

---

.github/workflows/pr.yml

Removes unnecessary `(#d+)` suffix check from PR title regex.

fix: remove unnecessary # suffix check form PR title regex

---

oracle/pkg/apiserver/apiserver.go

Renames the oracle api access fields so that they do not collide with the DD reserved state field.

refactor: rename oracle api access fields

---

contracts/contracts/validator-registry/avs/MevCommitAVS.sol
contracts/test/validator-registry/avs/EigenPodManagerMock.sol
contracts/test/validator-registry/avs/MevCommitAVSTest.sol

`ValidatorOptInRouter.sol` runs the following logic to determine if a validator is opted in: 
```solidity
function _isValidatorOptedIn(bytes calldata valBLSPubKey) internal view returns (bool) {
if (validatorRegistryV1.isValidatorOptedIn(valBLSPubKey)) {
return true;
}
return mevCommitAVS.isValidatorOptedIn(valBLSPubKey);
}
```
This function should return true or false without revert. 
Before this PR, `mevCommitAVS.isValidatorOptedIn` would revert if the function was called with a public key for which `_eigenPodManager.getPod` returned an address that did not correspond to a deployed eigenpod. Ie. reverts would occur when `validatorPubkeyToInfo` was called on an undeployed contract. To fix this issue, we first check `_eigenPodManager.hasPod`, and only continue the function if an eigen pod …

fix: check "hasPod" in _isValidatorOptedIn

---

contracts/Makefile
contracts/contracts/validator-registry/avs/MevCommitAVSV2.sol
contracts/scripts/validator-registry/avs/UpgradeAVS.s.sol
contracts/test/validator-registry/avs/EigenPodManagerMock.sol
contracts/test/validator-registry/avs/MevCommitAVSTest.sol

Changes enabling an upgrade of the deployed `MevCommitAVS` on Holesky, to incorporate this fix: https://github.com/primev/mev-commit/pull/353. Note the existing contract that needs to be upgraded was deployed from `v0.5.0`, hence this PR is into the `release/v0.5.x` branch.

feat: upgrade MevCommitAVS to v2 on Holesky

---

infrastructure/nomad/cluster.sh
infrastructure/nomad/playbooks/deploy.yml
infrastructure/nomad/playbooks/destroy.yml
infrastructure/nomad/playbooks/init.yml
infrastructure/nomad/playbooks/templates/jobs/mev-commit-geth.nomad.j2
infrastructure/nomad/playbooks/templates/services/nomad.hcl.j2

Enables automatic import/export of chaindata when Geth starts/stops.

feat: enable backup/restore of Geth db

---

infrastructure/nomad/playbooks/destroy.yml

Sets stop and purge jobs as the default on destroy unless the `---backup` flag is specified.

refactor: force stop and purge jobs as default on destroy

---

infrastructure/nomad/playbooks/templates/jobs/contracts-deployer.nomad.j2
infrastructure/nomad/playbooks/templates/jobs/mev-commit-bridge.nomad.j2
infrastructure/nomad/playbooks/templates/jobs/mev-commit-emulator.nomad.j2
infrastructure/nomad/playbooks/templates/jobs/mev-commit-faucet.nomad.j2
infrastructure/nomad/playbooks/templates/jobs/mev-commit-funder.nomad.j2
infrastructure/nomad/playbooks/templates/jobs/mev-commit-geth.nomad.j2
infrastructure/nomad/playbooks/templates/jobs/mev-commit-oracle.nomad.j2
infrastructure/nomad/playbooks/templates/jobs/mev-commit.nomad.j2
infrastructure/nomad/playbooks/templates/jobs/otel-collector.nomad.j2

Use `exec` to start all services inside the nomad task as pid 1. This will also fix the propagation of OS signals to these running services.

refactor: run all services inside nomad task as pid 1

---

infrastructure/nomad/playbooks/templates/services/nomad.hcl.j2

Doubles the limit from https://github.com/primev/mev-commit/pull/184 again, as I'm seeing the following error in #383 
```
"DownloadError": "failed to download artifact \"[http://10.1.0.13:1111/contracts_1bd12c5-1725606484.tar.gz\](http://10.1.0.13:1111/contracts_1bd12c5-1725606484.tar.gz/)": getter subprocess failed: exit status 1: failed to download artifact: tar archive contains too many files: 8193 > 8192",
```

refactor: double nomad decompression file count limit again

---

.github/workflows/ci.yml

The forge coverage command has been very flaky lately. Recent comments from [this issue](https://github.com/foundry-rs/foundry/issues/3357) confirm others are having trouble lately as well. The command itself suggests our use of `--ir-minimum` is a workaround. 
Example error from https://github.com/primev/mev-commit/actions/runs/10807042835/job/29977007439?pr=395
```
forge clean && forge coverage --ir-minimum
Warning! "--ir-minimum" flag enables viaIR with minimum optimization, which can result in inaccurate source mappings.
Only use this flag as a workaround if you are experiencing "stack too deep" errors.
Note that "viaIR" is only available in Solidity 0.8.13 and above.
See more: https://github.com/foundry-rs/foundry/issues/3357
Compiling …
```

chore: remove forge coverage command

---

contracts/contracts/validator-registry/VanillaRegistry.sol
contracts/test/validator-registry/VanillaRegistryTest.sol

Changes behavior of vanilla registry to match requested behavior for symbiotic solution. Unstaking validators who're slashed will no longer have their unstaking height reset. If a validator is slashed there's no need to punish them further by delaying the ability to fully deregister.

feat: dont reset unstake height upon slashing w/ vanilla registry

---

infrastructure/nomad/playbooks/templates/jobs/contracts-deployer.nomad.j2
infrastructure/nomad/playbooks/templates/jobs/datadog-agent.nomad.j2
infrastructure/nomad/playbooks/templates/jobs/mev-commit-bridge.nomad.j2
infrastructure/nomad/playbooks/templates/jobs/mev-commit-emulator.nomad.j2
infrastructure/nomad/playbooks/templates/jobs/mev-commit-faucet.nomad.j2
infrastructure/nomad/playbooks/templates/jobs/mev-commit-funder.nomad.j2
infrastructure/nomad/playbooks/templates/jobs/mev-commit-geth.nomad.j2
infrastructure/nomad/playbooks/templates/jobs/mev-commit-oracle.nomad.j2
infrastructure/nomad/playbooks/templates/jobs/mev-commit.nomad.j2
infrastructure/nomad/playbooks/templates/jobs/otel-collector.nomad.j2

This prevents other Nomad services from automatically restarting when the relevant template is changed.

fix: avoid restarting nomad services on template change

---

contracts-abi/abi/VanillaRegistry.abi
contracts-abi/clients/VanillaRegistry/VanillaRegistry.go
contracts/contracts/interfaces/IVanillaRegistry.sol
contracts/contracts/validator-registry/VanillaRegistry.sol
contracts/scripts/validator-registry/DeployVanillaRegistry.s.sol
contracts/test/validator-registry/VanillaRegistryTest.sol

VanillaRegistry has a minStake parameter (stake defining a validator as opted-in) that's different from the slashAmount of ETH that can be slashed by the oracle. These two parameters should always be the same. In that we don't need validators to lock up eth that isn't slashable, and slashing the same validator twice wouldn't make sense.

feat: consolidate slashAmount and minStake for vanillaRegistry

---

oracle/pkg/updater/updater.go
p2p/pkg/rpc/provider/export_test.go
p2p/pkg/rpc/provider/service.go
p2p/pkg/rpc/provider/service_test.go
x/contracts/events/publisher/http.go
x/contracts/txmonitor/eth_helper.go

1. Allow HTTP event listener to retry on failed RPC call.
2. Allow oracle updater to ignore errors after retries to proceed.
3. Return early in provider if provider API has no consumers.
4. Logs cleanup

fix: misc fixes from negative testing

---

contracts/contracts/validator-registry/avs/MevCommitAVS.sol
contracts/contracts/validator-registry/avs/README.md
contracts/test/validator-registry/avs/MevCommitAVSTest.sol

`VanillaRegistry` and `MevCommitMiddleware` both request validator deregistration upon a validator being slashed. See [here](https://github.com/primev/mev-commit/blob/f5b98b4cd90f5ed7d66ee87489a6a6f313677c99/contracts/contracts/validator-registry/VanillaRegistry.sol#L357) and [here](https://github.com/primev/mev-commit/blob/f5b98b4cd90f5ed7d66ee87489a6a6f313677c99/contracts/contracts/validator-registry/middleware/MevCommitMiddleware.sol#L544). To be consistent, `MevCommitAVS` now requests deregistration upon a validator being frozen (MevCommitAVS's equivalent to slashing).

fix: dereg validators on freeze

---

contracts/contracts/validator-registry/VanillaRegistry.sol
contracts/contracts/validator-registry/avs/MevCommitAVS.sol

Introduces local storage variables to `VanillaRegistry` and `MevCommitAVS` functions to reduce storage reads and therefore gas usage. A few existing variables were changed from `memory` to storage to also save on gas. 
This PR should be entirely a refactor so tests should remain unchanged.

perf: gas optimizations for vanillaRegistry and mevCommitAVS

---

p2p/pkg/rpc/provider/service.go
p2p/pkg/rpc/provider/service_test.go

Fixes get_stake provider api behavior which would always return an empty bls pubkey string

fix: get_stake provider api

---

launchmevcommit

Fixes an issue where the output logs were outputting the wrong node type for the provider.

fix: node type info in output logs

---

launchmevcommit

Introduces the `--nat-ip` flag for launchmevcommit to allow providers to set ip and/or port if they are behind NAT.

feat: introduce the --nat-ip flag for launchmevcommit

---

infrastructure/nomad/playbooks/templates/jobs/mock-l1.nomad.j2
infrastructure/nomad/playbooks/variables/profiles.yml

Closes #288 
This PR simply spins up a local [geth dev mode](https://geth.ethereum.org/docs/developers/dapp-developer/dev-mode) chain from the latest geth release, with 10 ETH only allocated to the contract deployer. The mock L1 is available at port 9545.
Using geth's dev mode is simpler and easier to configure than the [previous solution](https://github.com/primev/mev-commit-geth/tree/master/geth-poa/local-l1) which spun up a clique chain. 
This PR will enable further efforts in bridge and validator registry devnet testing

feat: introduce mock l1 for devnet setup

---

p2p/pkg/preconfirmation/preconfirmation.go

The timeout for `ProcessBid` operation which communicates with the provider API is too small. Increasing it to 15 secs.

fix: increase bid processing timeout

---

cl/cmd/redisapp/main.go
cl/geth-setup/genesis.json
cl/redisapp/leader.go
cl/redisapp/rapp.go
cl/redisapp/state.go
cl/redisapp/steps.go
cl/redisapp/steps_test.go

In our consensus layer, we aim to timestamp blocks without relying on the system clock to avoid inconsistencies due to system time adjustments or drifts. Instead, we will use the time difference between engine API calls for setting the block time.
**Block Processing with Engine API Calls:**
For each block, we make 4 engine API calls.
The block time is set in the first engine API call of each block.
**Measuring Time between Blocks:**
To avoid relying on system clock time, we measure the difference in time (let's call this diff) between the first engine API call of Block 1 and the first engine API call of Block 2.
This diff gives us a precise indication of how much time has passed between blocks without depending on the system clock.
**Setting the Timestamp Based on Measured Diff**:
If diff …

fix: update time setting

---

contracts-abi/abi/L1Gateway.abi
contracts-abi/clients/L1Gateway/L1Gateway.go
contracts/contracts/interfaces/IAllocator.sol
contracts/contracts/standard-bridge/Allocator.sol
contracts/contracts/standard-bridge/Gateway.sol
contracts/contracts/standard-bridge/L1Gateway.sol
contracts/contracts/standard-bridge/L1GatewayStorage.sol
contracts/test/standard-bridge/EventReceiver.sol
contracts/test/standard-bridge/L1GatewayTest.sol
contracts/test/standard-bridge/RevertingReceiver.sol
contracts/test/standard-bridge/SettlementGatewayTest.sol

Fixes https://cantina.xyz/code/4ee8716d-3e0e-4f59-b90d-aa56bf3b484c/findings/775. Note there were a lot of duplicates for this finding in the audit competition.
The solution taken in this PR is to handle failed ETH transfers in `finalizeTransfer`, by allowing those failed transfers to be manually retried again on the destination chain.

fix: malicious user can dos bridge transfer finalization 

---

p2p/cmd/main.go
p2p/pkg/node/node.go
p2p/pkg/preconfirmation/preconfirmation.go
p2p/pkg/preconfirmation/preconfirmation_test.go
p2p/pkg/rpc/bidder/service.go
p2p/pkg/rpc/bidder/service_test.go

There is a timeout on the bidder node as well for waiting for preconfs. This was not changed in the previous version. Adding this as a configurable option on the bidder node.
Also, adding categories to flags to make it easier for users.
```
NAME:
mev-commit - Start mev-commit node
USAGE:
mev-commit [global options] command [command options]
VERSION:
v0.6.0-23-g69cb1b5d-rev-69cb1b5-dirty
COMMANDS:
help, h  Shows a list of commands or help for one command
GLOBAL OPTIONS:
--help, -h     show help
--version, -v  print the version
API options
--http-addr value               Address to bind for http connections [$MEV_COMMIT_HTTP_ADDR]
--http-port value               Port to listen for http connections (default: 13523) [$MEV_COMMIT_HTTP_PORT]
--rpc-addr value                Address to bind for …
```

chore: add bid timeout option

---

contracts/scripts/core/DeployCore.s.sol
contracts/scripts/standard-bridge/DeployStandardBridge.s.sol
infrastructure/nomad/playbooks/deploy.yml
infrastructure/nomad/playbooks/templates/jobs/l1-transactor.nomad.j2
infrastructure/nomad/playbooks/templates/jobs/mev-commit-funder.nomad.j2
infrastructure/nomad/playbooks/variables/profiles.yml

Redistributes funds from single genesis address

refactor: redistribute funds from single genesis address

---

infrastructure/nomad/playbooks/deploy.yml
infrastructure/nomad/playbooks/variables/profiles.yml

Allocates faucet keystore in genesis for testnet/devnet.

fix: allocate faucet keystore in genesis

---

contracts/contracts/validator-registry/middleware/MevCommitMiddleware.sol

Adds two missing whenNotPaused modifiers to the middleware contract. This was found from a final passthrough of the contracts.

fix: add missing whenNotPaused modifiers

---

contracts/contracts/validator-registry/README.md
contracts/contracts/validator-registry/avs/README.md
contracts/scripts/MainnetConstants.sol
contracts/scripts/validator-registry/DeployVanillaRegistry.s.sol
contracts/scripts/validator-registry/avs/DeployAVS.s.sol
contracts/scripts/validator-registry/avs/ReleaseAddrConsts.sol

Adds mainnet deploy scripts for vanilla and avs registries. Also adds some documentation on the recommended values for contract params.

chore: mainnet deploy scripts for vanilla and avs registries

---

p2p/integrationtest/provider/client.go
p2p/pkg/node/node.go
testing/pkg/orchestrator/orchestrator.go

Changes the log level from error to warning for unsuccessful GRPC dial attempt(s).

refactor: change the log level from error to warn for failed grpc dial

---

.github/workflows/infrastructure.yml
infrastructure/nomad/playbooks/variables/profiles.yml
testing/cmd/main.go
testing/pkg/tests/staking/staking.go

fix: relay integration test

---

contracts/Makefile
contracts/scripts/validator-registry/GetParams.s.sol
contracts/scripts/validator-registry/avs/DeployAVS.s.sol

Adds scripts for querying current on-chain params for mainnet contracts. Changes to docs will accompany this PR once merged

chore: scripts for getting validator registry params on mainnet

---

infrastructure/nomad/playbooks/templates/jobs/mock-l1.nomad.j2
p2p/pkg/p2p/libp2p/internal/handshake/handshake.go
p2p/pkg/preconfirmation/store/store.go
p2p/pkg/preconfirmation/tracker/tracker.go
p2p/pkg/storage/pebble/pebble.go

Minor fixes in preconf tracker package to not stop on error. This routine is essential for tracking and opening commitments. So we should not error out unless it is some critical issue.
Also bumping handshake version for release.

fix: ignore errors in preconf tracker and bump handshake

---

.github/workflows/infrastructure.yml
infrastructure/nomad/playbooks/deploy.yml
infrastructure/nomad/playbooks/templates/jobs/contracts-deployer.nomad.j2
infrastructure/nomad/playbooks/templates/jobs/mev-commit-dashboard.nomad.j2
infrastructure/nomad/playbooks/templates/jobs/mev-commit-funder.nomad.j2
infrastructure/nomad/playbooks/templates/jobs/mev-commit-geth.nomad.j2
infrastructure/nomad/playbooks/templates/jobs/mev-commit-oracle.nomad.j2
infrastructure/nomad/playbooks/templates/jobs/mev-commit.nomad.j2
infrastructure/nomad/playbooks/templates/jobs/relay-emulator.nomad.j2
infrastructure/nomad/playbooks/variables/profiles.yml

Introduces new stressnet profile with L1 holesky.

feat: introduce stressnet-wl1

---

bridge/standard/cmd/user_cli/main.go
contracts-abi/config/testnet.go
infrastructure/nomad/playbooks/templates/jobs/contracts-deployer.nomad.j2

Currently it is using our mev-commit chain ID to issue the transaction to holesky for contract deployment.

fix: set L1 chain ID for holesky

---

contracts/contracts/validator-registry/middleware/MevCommitMiddleware.sol
contracts/contracts/validator-registry/middleware/MevCommitMiddlewareStorage.sol
contracts/contracts/validator-registry/middleware/README.md
contracts/test/validator-registry/middleware/MevCommitMiddlewareTest.sol

Adds support for Symbiotic's operator specific delegators. These types of delegators should be fully compatible with our middleware and are the most simple type of delegator (a vault can only allocate stake to a single operator).
See https://docs.symbiotic.fi/modules/vault/delegator#operatorspecificdelegator

feat: support for operator specific delegators

---

.gitmodules
contracts-abi/abi/MevCommitMiddleware.abi
contracts-abi/clients/MevCommitMiddleware/MevCommitMiddleware.go
contracts/contracts/interfaces/IMevCommitMiddleware.sol
contracts/contracts/validator-registry/middleware/MevCommitMiddleware.sol
contracts/contracts/validator-registry/middleware/MevCommitMiddlewareStorage.sol
contracts/contracts/validator-registry/middleware/README.md
contracts/remappings.txt
contracts/scripts/validator-registry/middleware/DeployMiddleware.s.sol
contracts/scripts/validator-registry/middleware/DeployMiddlewareWithMocks.s.sol
contracts/scripts/validator-registry/middleware/ReleaseAddrConsts.s.sol
contracts/test/validator-registry/middleware/MevCommitMiddlewareTest.sol
contracts/test/validator-registry/middleware/MevCommitMiddlewareTestCont.sol
contracts/test/validator-registry/middleware/MockBurnerRouter.sol
contracts/test/validator-registry/middleware/MockVault.sol

Vaults are now required to use a [burner router](https://docs.symbiotic.fi/modules/extensions/burners#burner-router) to integrate with our middleware contract. 
Concrete changes w.r.t above goal:
* Added vault config validation around integration with burner router. Delay and receiver config is enforced. 
* Added middleware storage for enforced slash receiver, enforced min router delay, and symbiotic `burnerRouterFactory` contract. 
*  Added forge dependency to https://github.com/symbioticfi/burners/tree/main
* Added related setters
* Docs to explain burner router requirements, and required trust assumptions with vaults.

feat: symbiotic burner router integration

---

bridge/standard/pkg/gwcontract/gateway.go
bridge/standard/pkg/gwcontract/gateway_test.go
bridge/standard/pkg/relayer/relayer.go
bridge/standard/pkg/relayer/relayer_test.go
contracts-abi/abi/L1Gateway.abi
contracts-abi/abi/SettlementGateway.abi
contracts-abi/clients/L1Gateway/L1Gateway.go
contracts-abi/clients/SettlementGateway/SettlementGateway.go
contracts/contracts/interfaces/IGateway.sol
contracts/contracts/standard-bridge/Gateway.sol
contracts/contracts/standard-bridge/GatewayStorage.sol
contracts/contracts/standard-bridge/L1Gateway.sol
contracts/contracts/standard-bridge/SettlementGateway.sol
contracts/scripts/standard-bridge/DeployStandardBridge.s.sol
contracts/test/standard-bridge/L1GatewayTest.sol
contracts/test/standard-bridge/SettlementGatewayTest.sol

Fixes https://cantina.xyz/code/d35ebc75-9107-4e58-a923-f81725912138/findings/10
* Removes `GatewayStorage.finalizationFee` from the storage of the gateway contracts. Each gateway still stores what's currently defined as `GatewayStorage.counterpartyFee` (now renamed to `counterpartyFinalizationFee`). 
* `TransferInitiated` event is augmented to emit this `counterpartyFinalizationFee`. 
* `finalizeTransfer` is augmented to accept a finalization fee as a part of the transfer being finalized. The relayer would be responsible for ensuring that the` _finalizationFee` value in `finalizeTransfer` is the same as what was specified as `counterpartyFinalizationFee` in the corresponding `TransferInitiated` event.
By making these changes, we remove the need for one gateway's counterpartyFee to match …

fix: use single on-chain bridge fee 

---

bridge/standard/cmd/relayer/main.go
bridge/standard/pkg/node/node.go
infrastructure/nomad/playbooks/templates/jobs/mev-commit-bridge.nomad.j2
infrastructure/nomad/playbooks/variables/profiles.yml

Use multiple RPC URLs for bridge for failover incase one of them is down.

feat: use multiple RPCs for relayer

---

infrastructure/nomad/playbooks/templates/jobs/contracts-deployer.nomad.j2

Updates the bridge finalization fee for L1. The fee for the mev-commit chain remains nominal since the relayer doesn't have to pay for tx fees

chore: update bridge finalization fee

---

p2p/integrationtest/provider/client.go
p2p/integrationtest/provider/main.go

chore: fix stressnet with new BLS keys

---

infrastructure/nomad/playbooks/templates/jobs/contracts-deployer.nomad.j2

Allows L1Gateway etherscan verification to work

fix: deploy l1 gateway directly from contracts dir

---

infrastructure/nomad/playbooks/templates/jobs/contracts-deployer.nomad.j2

See https://github.com/foundry-rs/foundry/pull/9551. The previous `-v` flag is now `-i`

fix: foundryup renamed -v flag to -i

---

infrastructure/nomad/playbooks/templates/jobs/mev-commit.nomad.j2
p2p/cmd/main.go
p2p/pkg/node/node.go
p2p/pkg/rpc/validator/service.go
p2p/pkg/rpc/validator/service_test.go

Use the same lag as oracle while querying for opted-in validators

fix: validator check lag

---

contracts/scripts/core/DeployCore.s.sol
contracts/scripts/standard-bridge/DeployStandardBridge.s.sol
infrastructure/nomad/playbooks/deploy.yml
tools/relay-emulator/main.go

Updates bridge hardcoded account balance assumptions for mainnet

chore: update bridge hardcoded values

---

contracts/entrypoint.sh
contracts/scripts/core/DeployCore.s.sol
infrastructure/nomad/playbooks/templates/jobs/contracts-deployer.nomad.j2
infrastructure/nomad/playbooks/templates/jobs/mev-commit-bridge.nomad.j2
infrastructure/nomad/playbooks/templates/jobs/mev-commit-dashboard.nomad.j2
infrastructure/nomad/playbooks/templates/jobs/mev-commit-geth.nomad.j2
infrastructure/nomad/playbooks/templates/jobs/mev-commit-oracle.nomad.j2
infrastructure/nomad/playbooks/templates/jobs/mev-commit.nomad.j2
infrastructure/nomad/playbooks/variables/environments.yml
infrastructure/nomad/playbooks/variables/profiles.yml

feat: introduce mainnet profile

---

contracts/scripts/standard-bridge/DeployStandardBridge.s.sol
infrastructure/nomad/playbooks/templates/jobs/contracts-deployer.nomad.j2
infrastructure/nomad/playbooks/variables/environments.yml

The changes from https://github.com/primev/mev-commit/pull/545 into https://github.com/primev/mev-commit/pull/544 were seemingly lost during a rebase. This PR reintroduces the necessary changes to main

fix: use primev multisig as l1 gateway owner addr

---

bridge/standard/cmd/user_cli/main.go
contracts-abi/config/config.go
contracts-abi/config/mainnet.go
contracts-abi/config/testnet.go
infrastructure/nomad/playbooks/variables/environments.yml
launchmevcommit
oracle/cmd/main.go
p2p/cmd/main.go
tools/dashboard/main.go

Sets all config values to the mainnet.

chore: update all configs to mainnet

---

bridge/standard/cmd/user_cli/main.go
contracts-abi/config/mainnet.go
oracle/cmd/main.go
p2p/cmd/main.go
tools/dashboard/main.go

Builds off https://github.com/primev/mev-commit/pull/551:
* `MainnetContracts` changed to `MevCommitChainContracts` since "mainnet" has its own meaning as mainnet L1 ethereum. 
* RPC addresses for bridge user cli were not updated to mainnet

chore: mainnet config fixes

---

x/contracts/txmonitor/canceller.go

The cancellation transaction was not being priced correctly.

fix: cancellation transaction

---

tools/bidder-cli/main.go

Bidder CLI hardcodes chain ID. Use it from RPC.

fix: use chain ID from RPC

---

contracts/scripts/MainnetConstants.sol
contracts/scripts/validator-registry/DeployVanillaRegistry.s.sol
contracts/scripts/validator-registry/avs/DeployAVS.s.sol

Adds a constant for the "commitment holdings address" which will be used on L1 to received slashed funds from any of the validator registries

chore: introduce commitment holdings address

---

infrastructure/nomad/cluster.sh
infrastructure/nomad/playbooks/templates/jobs/mev-commit-oracle.nomad.j2
infrastructure/nomad/playbooks/variables/profiles.yml

Introduces oracle-relay-urls flag for cluster script.

feat: introduce oracle-relay-urls flag for cluster script

---

infrastructure/nomad/playbooks/templates/jobs/contracts-deployer.nomad.j2

Prevents smart contracts from being redeployed if the Contract Deployer job is restarted and the contracts have already been deployed.

refactor: avoid contract redeployment on restart

---

contracts/scripts/validator-registry/middleware/ExampleSetup.s.sol

Symbiotic example scripts now use mainnet contract values. This matches examples from https://docs.primev.xyz/v1.0.0/get-started/validators/symbiotic

chore: use mainnet contract values in symbiotic example

---

p2p/pkg/node/node.go

The txmonitor should be started before we start making transactions. This component rate-limits txns based on account nonces. So if it is not started a higher nonce could be considered invalid.

fix: autodeposit during node init

---

contracts/contracts/utils/AlwaysFalseMiddleware.sol
contracts/scripts/validator-registry/DeployValidatorOptInRouter.s.sol

Removes the stand-in "always false" middleware contract that was temporarily used on mainnet. We've deployed the actual  middleware contract on mainnet now https://docs.primev.xyz/v1.0.0/developers/mainnet#l1-validator-registries

chore: remove stand-in middleware contract for mainnet

---

contracts/contracts/validator-registry/VanillaRegistry.sol

* Updates to [this](https://github.com/OpenZeppelin/openzeppelin-upgrades/releases/tag/%40openzeppelin%2Fupgrades-core%401.42.1) new release that fixes the build issues
* Adds pausable_init call for vanilla registry (seemed to be missing) @shaspitz - can you take a look at this?

chore: fix ci pipeline

---

.github/workflows/infrastructure.yml

Pin the version of Ethereum to the specific version that contains the bootnode tool.

fix: pin Ethereum version in infrastructure workflow

---

infrastructure/nomad/playbooks/variables/profiles.yml

Without that fix I'm not able to run a stressnet, facing that issue:
```
Placement Failures
mev-commit-bidder-emulator-nodes-group 
4 unplaced
Resources exhausted on 1 node
Dimension network: reserved port collision metrics=8181 exhausted on 1 node
```

fix: removed static port from bidder emulator

---

p2p/pkg/node/node.go

Seeing the following panic after changes to autodeposit closer flow. Better way is to close the DB in the end.
```
panic: pebble: closed
goroutine 126481 [running]:
github.com/cockroachdb/pebble.(*DB).newIter(0x459c00?, {0x1e18040?, 0x2bc51e0?}, 0x4?, {0x4?, 0x0?}, 0xc00099ba40?)
/home/aloknerurkar/go/pkg/mod/github.com/cockroachdb/pebble@v1.1.2/db.go:1011 +0x585
github.com/cockroachdb/pebble.(*DB).NewIterWithContext(...)
/home/aloknerurkar/go/pkg/mod/github.com/cockroachdb/pebble@v1.1.2/db.go:1503
github.com/cockroachdb/pebble.(*DB).NewIter(0xc001373f80?, 0x19328d7?)
/home/aloknerurkar/go/pkg/mod/github.com/cockroachdb/pebble@v1.1.2/db.go:1497 +0x2b
github.com/primev/mev-commit/p2p/pkg/storage/pebble.(*pebbleStorage).WalkPrefix(0xc000134548, {0x19328d7, 0x4}, 0xc0013725e8) …
```

fix: closing autodepositor

---

p2p/cmd/main.go
p2p/pkg/node/node.go
p2p/pkg/rpc/validator/export_test.go
p2p/pkg/rpc/validator/service.go
p2p/pkg/rpc/validator/service_test.go

Makes the notification offset for an opted-in proposer configurable upon p2p node init.

chore: configurable proposer notification offset

---

oracle/pkg/store/store.go

Oracle should not mark settlement as settled if the txn fails on chain. This would help identify the commitments that havent been settled and should be retried at some point.

fix: oracle only marks settled on success

---

tools/bidder-bot/bidder/beacon.go
tools/bidder-bot/bidder/bidder.go
tools/bidder-bot/monitor/monitor.go
tools/bidder-bot/monitor/monitor_test.go
tools/bidder-bot/service/balance.go
tools/bidder-bot/service/service.go
x/contracts/ethwrapper/client.go

For each sent bid, the bidder now monitors the following in a goroutine:
* Whether all commitments received
* Whether the tx landed on L1
For now, the output is just logs.
Additionally, the balance check for the bidder account now happens every hour instead of only on init.

feat: bidder bot monitor worker

---

tools/bidder-bot/bidder/bidder.go
tools/bidder-bot/main.go
tools/bidder-bot/notifier/beacon.go
tools/bidder-bot/notifier/export_test.go
tools/bidder-bot/notifier/full.go
tools/bidder-bot/notifier/full_test.go
tools/bidder-bot/notifier/notifier.go
tools/bidder-bot/notifier/selective.go
tools/bidder-bot/service/service.go

Introduces a new mode for the bidder bot where it uses a "full notifier", causing the bot to bid for every block. The old functionality uses a "selective notifier" where bids are only sent for opted-in proposers.

feat: introduce full bidder bot type

---

p2p/pkg/rpc/validator/service_test.go

* `TestProcessEpoch` now properly tests that expected notifications are firing, s.t. its a regression test for https://github.com/primev/mev-commit/pull/661
* It now tests for two opted in slot notifs, making it a better regression test for #661, which handles the first slot of an epoch in a special way

fix: test for processEpoch func

---

contracts-abi/clients/VanillaRegistry/VanillaRegistry.go
contracts-abi/script.sh
tools/points-service/main.go

The vanilla registry go binding was generated using its deprecated naming "validatorregistryv1". This PR fixes the binding to use the proper naming "vanillaregistry"

chore: update vanilla registry go binding

---

p2p/pkg/rpc/validator/export_test.go
p2p/pkg/rpc/validator/service.go
p2p/pkg/rpc/validator/service_test.go

Since mev-commit v1.1.1 release, missed slots have only ever happened for the first slot in an epoch. This fix is required so notifications for the first slot of an epoch are sent before the epoch starts.
We maintain the query that runs during the 'current epoch' for the 31 other slots, since validator duties are theoretically only stable within the current epoch. This means the notification for the first slot in an epoch is slightly less reliable than other notifs.
However I ran a [testing script](https://github.com/primev/validator-registry/blob/main/cmd/test-duties/main.go) for a few hours and didn't observe validator duties changing between epochs even once.

fix: properly handle first slot of epoch 

---

tools/bidder-bot/main.go
tools/bidder-bot/service/service.go

The "full" bidder bot sends bids for every L1 slot. Some providers accept all of these bids. But these bids will rarely result in a tx landing on L1. Meaning we should not monitor for l1 txes landing, specifically for the "full" configuration of the bidder bot

fix: full bidder bot no longer monitors l1 txes

---

oracle/pkg/updater/export_test.go
oracle/pkg/updater/updater.go
oracle/pkg/updater/updater_test.go

If a provider commits to a bid before the decay start time, it counts as fully decayed. It should instead not decay at all in this case. It is also realistic that providers may commit before, especially since we describe in the docs as a good practice for bidders to add ~300 ms to the current time to the start to not have any decay if providers commit "immediately".

fix: changed decay logic

---

p2p/pkg/node/node.go
p2p/pkg/notifications/notifications.go
p2p/pkg/stakemanager/stakemanager.go
p2p/pkg/stakemanager/stakemanager_test.go
testing/pkg/tests/connectivity/connectivity.go
x/contracts/events/events.go

feat: add stake manager

---

tools/points-service/api.go
tools/points-service/api_test.go

The points service's `all` endpoint now returns an empty array when requested pagination doesn't correspond to any DB rows, instead of returning "null". 
Fixes request from symbiotic team

fix: points service get-all endpoint

---

infrastructure/docker/Dockerfile.bidderemulator
infrastructure/docker/Dockerfile.l1transactor
infrastructure/docker/Dockerfile.provideremulator
infrastructure/docker/Dockerfile.relayemulator
p2p/integrationtest/provider/entrypoint.sh
p2p/integrationtest/provider/main.go
p2p/integrationtest/real-bidder/entrypoint.sh
p2p/integrationtest/real-bidder/main.go

Added docker files for supporting applications needed for devnet/stressnet testing.

feat: add docker files for supporting staff

---

contracts/contracts/interfaces/IRewardManager.sol
contracts/contracts/validator-registry/rewards/RewardManager.sol
contracts/test/validator-registry/rewards/RewardManagerTest.sol

The RewardsManager contract allows any rewards receiver address to set an override address which will then incur rewards on behalf of the receiver. Previously the contract included the option to `migrateExistingRewards` to the `msg.sender` when calling `removeOverrideAddress`. This created a vulnerability where a malicious attacker could set any address as the override address, then remove that override address, allowing the attacker to steal funds from anyone. 
Since this `migrateExistingRewards` flag was originally included only for UX purposes, we can remove it and prevent the described vulnerability.

fix: reward manager fund migration bug

---

contracts/contracts/validator-registry/rewards/RewardManager.sol

This PR changes the order that validator registries are queried during `RewardManager.payProposer`. 
See https://cantina.xyz/code/e92be0b9-b4f2-4bf2-9544-ae285fcfc02d/findings?finding=107
Our validator registries do not validate BLS identities/signatures on-chain. However, pubkeys can be manually slashed via any of the registries, disincentivizing spoofed validator registrations. 
The vanilla stake amount on mainnet is 1 eth, meaning the maximum punishment an attacker could incur is 1 eth in loss. Accumulated mev rewards for a pubkey can feasibly add up to more than 1 eth, possibly enabling an attacker to be profitable. The attacker could frontrun a valid receiver address from the `MevCommitMiddleware` contract for example, by registering a pubkey with accumulated rewards, to the vanilla …

fix: change order of registry queries in reward manager

---

contracts/contracts/validator-registry/VanillaRegistry.sol

https://github.com/primev/mev-commit/pull/584 introduced a change to the vanilla registry without following proper guidelines for contract upgrades. That change is reverted in this PR and will be included in a proper contract upgrade PR

chore: rm pauseable init change

---

infrastructure/charts/mev-commit-dashboard/Chart.yaml
infrastructure/charts/mev-commit-dashboard/templates/_helpers.tpl
infrastructure/charts/mev-commit-dashboard/templates/configmap.yaml
infrastructure/charts/mev-commit-dashboard/templates/deployment.yaml
infrastructure/charts/mev-commit-dashboard/templates/service.yaml
infrastructure/charts/mev-commit-dashboard/values.yaml

feat: add dashboard service helm chart

---

contracts/contracts/core/RegistryUpgradeLib.sol
contracts/scripts/core/UpgradeRegistries.s.sol

When testing the `UpgradeRegistries` on testnet, I found a couple issues to be fixed:
* Code from `RegistryUpgradeLib` must be pasted inline to avoid DELEGATECALL, causing ownership reverts
* console log statements are now correct

fix: provider/bidder registry upgrade script

---

p2p/pkg/preconfirmation/store/store.go
p2p/pkg/preconfirmation/store/store_test.go
p2p/pkg/preconfirmation/tracker/tracker_test.go
p2p/pkg/rpc/bidder/service.go
p2p/pkg/rpc/bidder/service_test.go
p2p/pkg/rpc/provider/service.go
p2p/pkg/rpc/provider/service_test.go

Use limits in the database query itself instead of getting everything and then using slice tricks.

fix: list commitments with opts

---

tools/preconf-rpc/handlers/handlers.go

Do not return all the preconfirmed transactions in the getBlockByHash RPC. Only return the single preconfirmed transaction.
Also fix the amounts in the estimate queries to decimal instead of hex.

fix: block hash and amounts

---

infrastructure/docker/Dockerfile.bidderemulator
infrastructure/docker/Dockerfile.builder
infrastructure/docker/Dockerfile.l1transactor
infrastructure/docker/docker-bake.hcl
tools/bidder-emulator/bidder.go
tools/bidder-emulator/main.go
tools/bidder-emulator/transactor_account.go
tools/go.mod
tools/go.sum

feat: new bidder emulator

---

infrastructure/charts/mev-commit-preconf-rpc/Chart.yaml
infrastructure/charts/mev-commit-preconf-rpc/templates/_helpers.tpl
infrastructure/charts/mev-commit-preconf-rpc/templates/deployment.yaml
infrastructure/charts/mev-commit-preconf-rpc/templates/externalsecret.yaml
infrastructure/charts/mev-commit-preconf-rpc/templates/service.yaml
infrastructure/charts/mev-commit-preconf-rpc/values.yaml

feat: add preconf rpc chart

---

tools/preconf-rpc/blocktracker/blocktracker.go
tools/preconf-rpc/handlers/handlers.go
tools/preconf-rpc/main.go
tools/preconf-rpc/pricer/pricer.go
tools/preconf-rpc/pricer/pricer_test.go
tools/preconf-rpc/sender/sender.go
tools/preconf-rpc/sender/sender_test.go
tools/preconf-rpc/service/service.go
x/opt-in-bidder/bidder.go

This PR fixes some of the issues found in the initial testing of the RPC. It also improves the pricing strategy based on history.
- Bid timeout
It was observed that providers can simply not respond to the bid. The default timeout on the bidder node is 30s. We can reduce this but its better to control this ourselves.
- Pricing strategy
Previously we were always using the max confidence value of the blocknative API. Now we switch to an approach where we start with the 90% confidence and move up to 99 on the third attempt.
- Use Block native API with API Key

fix: improvements to pricing strategy

---

tools/preconf-rpc/handlers/handlers.go
tools/preconf-rpc/sender/sender.go
tools/preconf-rpc/sender/sender_test.go

Adds new cancel transaction RPC
#726

feat: add new cancel transaction RPC

---

tools/preconf-rpc/sender/sender.go
tools/preconf-rpc/sender/sender_test.go
x/opt-in-bidder/bidder.go

This is a small fix to estimate the opt in slot correctly. Previously we were not considering the time since the last block in the estimate.
Also in the bidder, we have increased the decay start timestamp delay to 200ms. This is more generous and gives providers some leeway to avoid decay. Also increased the decay time to twice the timeout. Which would make the bid decay atmost to half of its value if provider takes the entire timeout duration to respond. This is still crude but need to give more thought on pricing. Especially since we also need to consider clients which are setting the priority fee on their own.

fix: tuning bidding logic

---

.gitmodules

Bumps our https://github.com/foundry-rs/forge-std solidity dependency to latest release https://github.com/foundry-rs/forge-std/releases/tag/v1.10.0. This enables eip-7702 related cheatcodes for future prs, ex: https://getfoundry.sh/reference/cheatcodes/sign-delegation/

chore: bump forge-std

---

cl/blockbuilder/blockbuilder.go
cl/blockbuilder/blockbuilder_test.go
cl/redisapp/leaderfollower/leaderfollower.go

The current implementation of our consensus layer is exhibiting odd behavior where recently built block timestamps will jump up to 20 minutes ahead of system time. This PR streamlines implementation, removes unnecessary variables, and makes the logic easier to comprehend/debug. After testing, these changes have fixed the issue. 
* `bb.lastBlockTime` variable was being set independently from `bb.executionHead.BlockTime`. We now use existing `bb.executionHead.BlockTime` in-place
* `head` variable local to `GetPayload` was being set independently from `bb.executionHead`. We now use existing `bb.executionHead` in-place
* `loadExecutionHead` was removed. We now just set `bb.executionHead` once upon service restart in `setExecutionHeadFromRPC` and subsequently update `bb.executionHead` at the …

feat: simplify single node cl implementation 

---

tools/preconf-rpc/blocktracker/blocktracker.go
tools/preconf-rpc/blocktracker/blocktracker_test.go
tools/preconf-rpc/handlers/handlers.go
tools/preconf-rpc/pricer/pricer.go
tools/preconf-rpc/pricer/pricer_test.go
tools/preconf-rpc/rpcserver/rpcserver.go
tools/preconf-rpc/sender/sender.go
tools/preconf-rpc/sender/sender_test.go
tools/preconf-rpc/service/service.go

Add CORS headers in the responses.

fix: preconf RPC CORS headers

---

tools/preconf-rpc/sender/sender.go

- In some cases the sender was not getting triggered properly causing the txn to be stuck in the DB. Once a new txn comes in the trigger happens, but we need to be more aggresive.
- Added a timeout of 10m for txns. If it takes more than that, we fail the operation.

fix: issues from RPC testing

---

Makefile
infrastructure/charts/deploy.sh
infrastructure/charts/mev-commit-p2p/values-bidder.yaml
infrastructure/charts/mev-commit-p2p/values-provider.yaml

feat: allow local cluster builds

---

cl/cmd/singlenode/main.go
cl/go.mod
cl/go.sum
cl/singlenode/follower/follower.go
cl/singlenode/follower/follower_test.go
cl/singlenode/payloadstore/redis.go
cl/singlenode/payloadstore/redis_test.go
cl/singlenode/singlenode.go
cl/types/types.go
go.work.sum

Provides the option for both the leader and follower consensus clients to use redis instead of postgres for reading/writing payloads

feat: optional redis config for leader follower setup

---

.gitmodules
contracts-abi/abi/RocketMinipoolRegistry.abi
contracts-abi/clients/AlwaysFalseRegistry/AlwaysFalseRegistry.go
contracts-abi/clients/BlockRewardManager/BlockRewardManager.go
contracts-abi/clients/RewardDistributor/RewardDistributor.go
contracts-abi/clients/RocketMinipoolRegistry/RocketMinipoolRegistry.go
contracts-abi/clients/ValidatorOptInHub/ValidatorOptInHub.go
contracts-abi/script.sh
contracts/README.md
contracts/contracts/interfaces/IRocketMinipoolRegistry.sol
contracts/contracts/validator-registry/rocketpool/RocketMinipoolRegistry.sol
contracts/contracts/validator-registry/rocketpool/RocketMinipoolRegistryStorage.sol
contracts/l1-deployer-cli.sh
contracts/remappings.txt
contracts/scripts/validator-registry/rocketpool/DeployRocketMinipoolRegistry.s.sol
contracts/test/validator-registry/rocketpool/RocketMinipoolRegistryTest.sol

Adds a RocketPool validator registry for Mev-Commit. Operators register using validator pubkeys; we read ownership/status from Rocket Pool and only track minimal participation state on our side.
How it works: given a validator pubkey, we resolve pubkey → minipool via RocketStorage, read the node address from the minipool, and verify the minipool is active (“Staking”). We also read the node’s current withdrawal address. A call is authorized if msg.sender is either the node address or the withdrawal address. On success we mark the pubkey as registered in a tiny struct (exists, deregTimestamp, freezeTimestamp).
Key points:
Registration is free (gas only).
Both the node address and the withdrawal address can register, request deregistration, and finalize deregistration.
Freezing functionality …

feat: rocketpool registry for minipool operators
