p2p/integrationtest/real-bidder/main.go, p2p/pkg/preconfirmation/preconfirmation.go, p2p/pkg/rpc/bidder/service.go
Reorder preconfirmation sending to be more efficient.
=> chore: sending pre-conf before saving to sc

infrastructure/nomad/playbooks/templates/jobs/deploy-contracts.nomad.j2, infrastructure/nomad/playbooks/templates/jobs/mev-commit-funder.nomad.j2
updated foundry, as previous one is no longer available
=> chore: updated foundry

p2p/pkg/node/node.go, p2p/pkg/preconfirmation/metrics.go, p2p/pkg/preconfirmation/preconfirmation.go, p2p/pkg/signer/preconfencryptor/encryptor.go, p2p/pkg/signer/preconfencryptor/encryptor_test.go
* changed `json` marshalling to `proto`
* Set up keys for encryptor once, instead of getting it from the store every time
* Added new errors for the code cleanliness
=> chore: encryptor optimizations

p2p/pkg/depositmanager/deposit.go
* Adds details of window to give actionable feedback to user to resolve error.
=> feat: updates error for window balance

contracts/contracts/validator-registry/ValidatorRegistryV1.sol, contracts/contracts/validator-registry/avs/MevCommitAVS.sol, contracts/contracts/validator-registry/avs/README.md, contracts/test/validator-registry/ValidatorRegistryV1Test.sol, contracts/test/validator-registry/avs/MevCommitAVSTest.sol
Fixes bug IDs 1 through 4 from validator registry audit
=> fix: validator registry audit remediations part 1 

infrastructure/nomad/README.md
Adds the missing information to the `infrastructure/nomad/README.md` file.
=> docs(infra): update README.md

.github/workflows/artifacts.yml
Fixes the upload of built artifacts to S3.
=> fix: artifacts.yml action

oracle/pkg/apiserver/dashboard.go
=> fix: commitment stored event update

infrastructure/nomad/README.md
Updates `nomad/README.md` with info about existing build environment variables.
=> docs: update nomad/README file

oracle/pkg/l1Listener/l1Listener.go, oracle/pkg/node/node.go, oracle/pkg/node/node_test.go
- includes more context in errors and logs (block number, retry attempts, etc...)
- changes the severity of the failed attempt form error to a warning
- introduces a random retry interval
- add tests
=> refactor: oracle L1 retry client

p2p/pkg/apiserver/middleware.go, x/contracts/txmonitor/txmonitor.go
The status field is a reserved one in datadog. We should not use this tag in logs.
=> fix: remove status

infrastructure/nomad/playbooks/templates/jobs/mev-commit-emulator.nomad.j2, infrastructure/nomad/playbooks/templates/jobs/mev-commit.nomad.j2, infrastructure/nomad/playbooks/variables/profiles.yml, p2p/go.mod, p2p/go.sum, p2p/integrationtest/bidder/main.go, p2p/integrationtest/provider/client.go, p2p/integrationtest/provider/main.go, p2p/integrationtest/real-bidder/main.go, p2p/pkg/node/node.go, x/util/otelutil/otel.go
Enables instrumentation of GRPC API calls.
=> feat: instrument grpc API calls

contracts-abi/config/testnet.go, p2p/cmd/main.go, p2p/pkg/node/node.go, p2p/pkg/rpc/validator/service.go
* added default params for validator api
* added error check for the incorrect epoch
=> feat: added default params for validator api

launchmevcommit
- adds new flag to enable tracing
- adds new flag to set service name (as nickname)
=> feat: add new flags for launchmevcommit script 

.github/pull_request_template.md
Deleted the redundant check since we have integration tests in the CI pipeline.
=> chore: delete redundant check

contracts-abi/config/testnet.go, contracts/Makefile, contracts/scripts/validator-registry/DeployValidatorOptInRouter.s.sol
Updates contract values w.r.t. new validator opt-in router deployment.
=> chore: update contract values for new opt-in router deployment

infrastructure/nomad/playbooks/templates/jobs/mev-commit-geth.nomad.j2, infrastructure/nomad/playbooks/variables/profiles.yml
Changes sync mode to snap on all Geth nodes.
=> refactor: change sync mode to snap on all Geth nodes

infrastructure/nomad/playbooks/templates/jobs/mev-commit-geth.nomad.j2
Remove unneeded resources from Geth backup/restore tasks.
=> feat: tune Geth backup/restore resources

infrastructure/nomad/cluster.sh, infrastructure/nomad/playbooks/deploy.yml, infrastructure/nomad/playbooks/templates/jobs/mev-commit-geth.nomad.j2, infrastructure/nomad/playbooks/variables/profiles.yml
Introduces the Geth archive node profile, which allows to deploy a Geth archive node.
=> feat: introduce Geth archive node profile

infrastructure/nomad/playbooks/destroy.yml, infrastructure/nomad/playbooks/templates/jobs/mev-commit-geth.nomad.j2
Avoid running the main task if a backup is in progress.
=> fix: backup in progress

x/contracts/events/publisher/ws.go, x/contracts/events/publisher/ws_test.go
Retry subscription to logs on error. Allow sufficient time before we declare error.
=> fix: retry on failed event subscription

p2p/pkg/rpc/provider/service.go
=> fix: send payloads and reverting txns on API

contracts/Makefile, contracts/contracts/validator-registry/avs/MevCommitAVSV2.sol, contracts/scripts/validator-registry/avs/UpgradeAVS.s.sol, contracts/test/validator-registry/avs/EigenPodManagerMock.sol, contracts/test/validator-registry/avs/MevCommitAVSTest.sol
Reapplication of https://github.com/primev/mev-commit/pull/360 to the `release/v0.5.x` branch
=> feat: upgrade MevCommitAVS to v2 on Holesky (repeat)

contracts-abi/abi/MevCommitAVSV3.abi, contracts-abi/clients/MevCommitAVSV3/MevCommitAVSV3.go, contracts-abi/script.sh, contracts/Makefile, contracts/contracts/interfaces/IMevCommitAVSV3.sol, contracts/contracts/validator-registry/avs/MevCommitAVSStorageV3.sol, contracts/contracts/validator-registry/avs/MevCommitAVSV3.sol, contracts/scripts/validator-registry/avs/UpgradeAVSV2ToV3.s.sol, contracts/test/validator-registry/avs/MevCommitAVSTest.sol
Backports https://github.com/primev/mev-commit/pull/393 and implements code necessary for v2 -> v3 upgrade of `MevCommitAVS`
=> feat: upgrade MevCommitAVS to v3 on Holesky

oracle/pkg/updater/updater.go
=> fix: handle pq error

contracts/README.md
Updates contract upgrade readme to account for the fact that upgrades are relevant to the contract impl from the release branch, not the contract impl from main.
=> docs: update contract upgrade readme

infrastructure/nomad/playbooks/templates/jobs/mev-commit-bridge.nomad.j2, infrastructure/nomad/playbooks/templates/jobs/mev-commit-emulator.nomad.j2, infrastructure/nomad/playbooks/templates/jobs/mev-commit-geth.nomad.j2, infrastructure/nomad/playbooks/templates/jobs/mev-commit-oracle.nomad.j2, infrastructure/nomad/playbooks/templates/jobs/mev-commit.nomad.j2, x/util/otelutil/otel.go
- renames the service identifier from `service` to `service.name`
- introduces a service version identifier `service.version`
=> refactor: rename service identifier and introduce service version

infrastructure/nomad/playbooks/templates/jobs/mev-commit-geth.nomad.j2
Changes the default verbosity of all Geth nodes.
=> refactor: change log verbosity of Geth nodes

.github/workflows/infrastructure.yml, infrastructure/nomad/cluster.sh, infrastructure/nomad/playbooks/deploy.yml, infrastructure/nomad/playbooks/templates/jobs/mev-commit-geth.nomad.j2, infrastructure/nomad/playbooks/variables/profiles.yml
Introduces static node configuration to link all geth nodes.
=> refactor: introducing static node configuration to link all geth nodes

contracts-abi/abi/BidderRegistry.abi, contracts-abi/abi/Oracle.abi, contracts-abi/abi/PreconfManager.abi, contracts-abi/abi/ProviderRegistry.abi, contracts-abi/clients/BidderRegistry/BidderRegistry.go, contracts-abi/clients/Oracle/Oracle.go, contracts-abi/clients/PreconfManager/PreconfManager.go, contracts-abi/clients/ProviderRegistry/ProviderRegistry.go, contracts/contracts/core/BidderRegistry.sol, contracts/contracts/core/BidderRegistryStorage.sol, contracts/contracts/core/Oracle.sol, contracts/contracts/core/OracleStorage.sol, contracts/contracts/core/PreconfManager.sol, contracts/contracts/core/ProviderRegistry.sol, contracts/contracts/core/ProviderRegistryStorage.sol, contracts/contracts/interfaces/IBidderRegistry.sol, contracts/contracts/interfaces/IOracle.sol, contracts/contracts/interfaces/IPreconfManager.sol, contracts/contracts/interfaces/IProviderRegistry.sol, contracts/scripts/core/DeployCore.s.sol, contracts/test/core/BidderRegistryTest.sol, contracts/test/core/OracleTest.sol, contracts/test/core/PreconfManagerTest.sol, contracts/test/core/ProviderRegistryTest.sol
Fixes following issues from core contract audit report:
* Bug ID # 3
* Bug ID # 5
* Bug ID # 6, addressed by adding setters to state variables that did not have them, along with event emittance for every setter.
Also introduces misc general refactors
=> refactor: misc contract audit fixes

p2p/pkg/p2p/libp2p/internal/handshake/handshake.go
=> chore: bump version for new release

contracts-abi/abi/MevCommitMiddleware.abi, contracts-abi/clients/MevCommitMiddleware/MevCommitMiddleware.go, contracts/contracts/interfaces/IMevCommitMiddleware.sol, contracts/contracts/validator-registry/middleware/MevCommitMiddleware.sol, contracts/contracts/validator-registry/middleware/MevCommitMiddlewareStorage.sol, contracts/test/validator-registry/middleware/MevCommitMiddlewareTest.sol, contracts/test/validator-registry/middleware/MevCommitMiddlewareTestCont.sol
Fixes issues 1, 2, 5 for audit report on middleware contract.
=> feat: middleware fixes from audit report 

contracts-abi/config/testnet.go, p2p/pkg/node/node.go
The default contract addresses are updated. Also, small issue on provider node closing is fixed.
=> chore: update contract addresses and bug with provider exit

infrastructure/nomad/cluster.sh, infrastructure/nomad/playbooks/deploy.yml, infrastructure/nomad/playbooks/destroy.yml, infrastructure/nomad/playbooks/init.yml, infrastructure/nomad/playbooks/templates/jobs/mev-commit-geth.nomad.j2, infrastructure/nomad/playbooks/templates/services/nomad.hcl.j2
Replaces export/import tasks (before starting/after stopping) by storing Geth chaindata on the mounted host volume.
=> refactor: export/import of Geth chaindata

infrastructure/nomad/cluster.sh, infrastructure/nomad/playbooks/destroy.yml
Clears the host directory with the Geth data when a destroy call is made.
=> fix: remove Geth data on destroy

infrastructure/nomad/playbooks/deploy.yml, infrastructure/nomad/playbooks/templates/jobs/contracts-deployer.nomad.j2, infrastructure/nomad/playbooks/templates/jobs/mev-commit-faucet.nomad.j2, infrastructure/nomad/playbooks/templates/jobs/mev-commit-funder.nomad.j2, infrastructure/nomad/playbooks/templates/jobs/mev-commit-geth.nomad.j2, infrastructure/nomad/playbooks/templates/jobs/mev-commit-oracle.nomad.j2, infrastructure/nomad/playbooks/templates/jobs/mev-commit.nomad.j2, infrastructure/nomad/playbooks/templates/jobs/mock-l1.nomad.j2, infrastructure/nomad/playbooks/variables/profiles.yml
- allow multiple keystores in profiles.yml
- fixes L1 mock geth artifact architecture
=> refactor: allow multiple keystores

bridge/standard/bridge-v1/emulator/.goreleaser.yml, bridge/standard/bridge-v1/emulator/main.go, infrastructure/nomad/playbooks/templates/jobs/bridge-emulator.nomad.j2, infrastructure/nomad/playbooks/templates/jobs/l1-transactor.nomad.j2, infrastructure/nomad/playbooks/templates/jobs/mock-l1.nomad.j2, infrastructure/nomad/playbooks/variables/profiles.yml, tools/l1-transaction-emulator/.goreleaser.yml, tools/l1-transaction-emulator/main.go, tools/l1-transaction-emulator/transactor_account.go
=> fix: add transactor emulator

bridge/standard/bridge-v1/cmd/relayer/main.go
=> fix: bridge use keystore

contracts/Makefile, contracts/README.md, contracts/l1-deployer-cli.sh
Closes https://github.com/primev/mev-commit/issues/358
=> feat: l1 contract deployer cli

bridge/standard/cmd/user_cli/main.go, bridge/standard/pkg/transfer/transfer.go
Adding additional message to show waiting for finalization.
Renaming command to the binary name created in releases.
=> fix: new message and renaming command

contracts/l1-deployer-cli.sh
Adds `resume`, `priority-gas-price` and `with-gas-price` flags to the l1 deployer cli to assist with deployment when gas prices are volatile. Intended usage of these flags within `forge script` is [here](https://book.getfoundry.sh/reference/forge/forge-script)
=> chore: add flags to l1 deployer cli

.github/workflows/infrastructure.yml, infrastructure/nomad/playbooks/deploy.yml
=> fix: all targets build

p2p/integrationtest/provider/main.go
Fixes integration with provider.
=> fix: provider

bridge/standard/cmd/emulator/main.go, testing/pkg/tests/bridge/bridge.go
Adds context timeout to bridge transfer
=> refactor: add context timeout to bridge transfer

contracts/contracts/validator-registry/README.md, contracts/scripts/validator-registry/middleware/DeployMiddleware.s.sol
README inline with code was outdated. This updates it for having 3 forms of opt-in
=> docs: update validator reg inline docs 

contracts-abi/config/testnet.go, contracts/scripts/validator-registry/DeployValidatorOptInRouter.s.sol, infrastructure/nomad/playbooks/templates/jobs/contracts-deployer.nomad.j2
Updates default validator opt in router address with newest deployment. Also updates the deploy script for the router with latest MevCommitMiddleware contract 
Closes https://github.com/primev/mev-commit/issues/488
=> chore: updated router addr and deploy script

cl/redisapp/blockbuilder/blockbuilder_test.go
Fixed flaky tests
Fixes https://github.com/primev/mev-commit/issues/491
=> fix: fixed flaky tests

p2p/pkg/rpc/bidder/service.go
Added logs for the bidder service in case of errors
Fixes https://github.com/primev/mev-commit/issues/497
=> feat: added logs to bidder service

go.work.sum, infrastructure/nomad/playbooks/templates/jobs/contracts-deployer.nomad.j2, infrastructure/nomad/playbooks/templates/jobs/mev-commit-geth.nomad.j2, infrastructure/nomad/playbooks/templates/jobs/mock-l1.nomad.j2, infrastructure/nomad/playbooks/variables/profiles.yml, p2p/gen/go/bidderapi/v1/bidderapi.pb.gw.go, p2p/gen/go/debugapi/v1/debugapi.pb.gw.go, p2p/gen/go/providerapi/v1/providerapi.pb.gw.go, p2p/gen/go/validatorapi/v1/validatorapi.pb.gw.go
Introduces zero fee addresses for oracle, contract deployer, and bridge relayer
=> feat: add geth zero fee addresses

p2p/integrationtest/provider/main.go
=> fix: emulator ignores if no relay

infrastructure/nomad/playbooks/templates/jobs/mev-commit-emulator.nomad.j2
Fixes relay emulator for testnet.
=> fix: relay emulator for testnet

infrastructure/nomad/playbooks/templates/jobs/contracts-deployer.nomad.j2, infrastructure/nomad/playbooks/variables/profiles.yml
Set L1 RPC URL for l1-gateway contract deployment.
=> fix: set L1 RPC URL for gateway deployment

launchmevcommit
Fixes the log message containing faucet for testnet.
=> fix: launchmevcommit script logs

bridge/standard/cmd/user_cli/main.go
=> fix: remove required flags for bridge arguments

.github/workflows/releaser.yml, tools/bidder-cli/.goreleaser.yml
Adding the bidder-cli artefact for release. This tool has had good reviews from our internal testing, so adding this as part of the release from now.
=> chore: add bidder-cli artifact for release

p2p/pkg/p2p/libp2p/internal/handshake/handshake.go
Handshake version bump due to contract updates.
=> chore: bump handshake version

contracts/contracts/core/ProviderRegistry.sol, contracts/contracts/interfaces/IProviderRegistry.sol, p2p/pkg/rpc/provider/service.go
=> fix: txn opts for BLS registration and errors

contracts/contracts/utils/AlwaysFalseMiddleware.sol, contracts/scripts/validator-registry/DeployValidatorOptInRouter.s.sol
Mainnet deployment contract for validator opt-in router
=> chore: add mainnet deployment contract for validator opt-in router

static/avs-metadata.json
Updates description for https://app.eigenlayer.xyz/avs/0xbc77233855e3274e1903771675eb71e602d9dc2e using most up-to-date blurb
=> docs: update avs metadata json

contracts/scripts/standard-bridge/DeployStandardBridge.s.sol, infrastructure/nomad/playbooks/templates/jobs/contracts-deployer.nomad.j2
A PR into https://github.com/primev/mev-commit/pull/544
=> feat: use primev multisig as l1 gateway owner address on mainnet

contracts/contracts/core/BidderRegistry.sol, contracts/contracts/core/Oracle.sol, contracts/contracts/core/ProviderRegistry.sol
* Noticed the author tag still exists from legacy contract changes made in the early days.
* Recommend we remove this.
=> chore: remove author comment

oracle/pkg/updater/updater.go
Oracle has to send residual percentage for settlement.
=> fix: use residual percentage instead of decay

testing/pkg/tests/preconf/preconf.go
* Ensures bid reward is correctly calculated
=> feat: e2e check to ensure reward is correct

contracts/Makefile, contracts/scripts/validator-registry/middleware/ExampleSetup.s.sol
Adds example symbiotic scripts for vaults and operators to give them examples of the exact forge scripts they can run to achieve the steps from https://docs.primev.xyz/v1.0.0/get-started/validators/symbiotic
=> feat: symbiotic example scripts

infrastructure/nomad/playbooks/deploy.yml, infrastructure/nomad/playbooks/templates/jobs/mev-commit-geth.nomad.j2, infrastructure/nomad/playbooks/templates/jobs/mock-l1.nomad.j2
Include environment name in the genesis.json and config.toml file name.
=> refactor: include env in the genesis and config file name

contracts/scripts/validator-registry/middleware/DeployMiddleware.s.sol, contracts/scripts/validator-registry/middleware/ReleaseAddrConsts.s.sol
* Updates our symbiotic core reference to their latest release
* Updates our symbiotic burners reference to their latest release 
* Adds symbiotic mainnet deployment addresses
* Adds script for mainnet middleware deployment
=> feat: config for symbiotic mainnet deployment

.github/workflows/releaser.yml
Modifies the releaser.yml to allow release candidates.
=> chore: introduce release candidate tags

go.work.sum, infrastructure/nomad/playbooks/templates/jobs/points-service.nomad.j2, infrastructure/nomad/playbooks/variables/profiles.yml, tools/points-service/.goreleaser.yml, tools/points-service/main.go
Introduces points services nomad job.
=> feat: introduce points service nomad job

oracle/cmd/main.go, p2p/cmd/main.go
Lower default base and priority fee
=> fix: lower default base and priority fee

README.md, static/avs-metadata.json
=> chore: update protocol description

tools/points-service/main.go
* Adds very granular view of accrued points for users.
=> feat: granular accrual of points

tools/points-service/main.go
* Switches giving points from podowner to msg.sender
=> feat: gets msgsender for eignelayer

contracts/scripts/core/DeployPreconfManager.s.sol
Add script for preconf manager new deployment
=> feat: added preconf manager deployment

contracts/contracts/core/ProviderRegistryV2.sol, contracts/contracts/interfaces/IProviderRegistryV2.sol, contracts/scripts/core/UpgradeProviderRegistry.s.sol
Add script to update provider registry contract
=> feat: update provider registry

tools/points-service/.goreleaser.yml, tools/points-service/api.go, tools/points-service/main.go
* There were some small modifications required to the structure of the points api responses to adhere to symbiotic requirements
=> feat: updates api to adhere to symbiotic requirements

.github/workflows/infrastructure.yml, infrastructure/nomad/playbooks/templates/jobs/instant-bridge.nomad.j2, infrastructure/nomad/playbooks/variables/profiles.yml
Separate out the instant bridge job to be able to deploy on separate node.
=> fix: separate instant bridge deployment

infrastructure/nomad/playbooks/templates/jobs/mev-commit.nomad.j2
The instant bridge profile is used to deploy. So use env to check if we are using testnet/mainnet.
=> fix: update testnet values in job

contracts-abi/config/config.go, contracts-abi/config/mainnet.go, contracts-abi/config/testnet.go, p2p/cmd/main.go, p2p/pkg/node/node.go
Setting default params for contract addresses and urls based on chain id.
=> feat: set defaults

p2p/pkg/rpc/validator/export_test.go, p2p/pkg/rpc/validator/service.go, p2p/pkg/rpc/validator/service_test.go
Fixed bug with duplicate notifications
=> fix: fix double notificaions for validator api

contracts/contracts/core/OracleV2.sol, contracts/scripts/core/UpgradeOracle.s.sol
=> fix: added oracle upgrade

p2p/pkg/autodepositor/autodepositor.go, p2p/pkg/autodepositor/autodepositor_test.go
=> revert: add withdraw to autodeposit start

p2p/pkg/node/node.go
There was a bug introduced in the shutdown path of the node which cause the DB to not be flushed on close causing inconsistencies. This led to deposits being lost for the bidder and other loss of information.
The problem was that we reversed the order of closing all the components, which unearthed a dependency of the libp2p service closing on the notifications service. The p2p service waits to dispatch disconnected events which now send notifications. As the notification service is already shutdown, the dispatch of event is hung and as a result p2p service doesnt close. So the notification service should be stopped in the end to be safe.
=> fix: shutdown bug

.github/workflows/infrastructure.yml, infrastructure/nomad/playbooks/deploy.yml, infrastructure/nomad/playbooks/destroy.yml
Add auth to nomad infrastructure jobs. Added tokens to latitude machines and add them to github secrets. Set them up in the ansible playbooks.
=> feat: use nomad with auth for staging

oracle/pkg/node/node.go, oracle/pkg/store/store.go, oracle/pkg/updater/updater.go
Retry the failed settlements from v1.1.0 version. The settlements that have failed have the status "execution reverted". This change is a temporary change for the patch release to retry these failed settlements.
=> fix: retry failed settlements in oracle

p2p/pkg/node/node.go
Fixed url order for validator service
=> fix: fixed url order

infrastructure/nomad/playbooks/variables/profiles.yml, testing/pkg/tests/deposit/deposit.go, testing/pkg/tests/preconf/preconf.go
Now that CI runs in a relatively stable way, we can reduce the time of the tests without causing any risk of regression.
=> chore: reduce CI time

contracts/.solhint.json, contracts/contracts/core/BidderRegistry.sol, contracts/contracts/core/BlockTracker.sol, contracts/contracts/core/Oracle.sol, contracts/contracts/core/PreconfManager.sol, contracts/contracts/core/ProviderRegistry.sol, contracts/contracts/interfaces/IBidderRegistry.sol, contracts/contracts/standard-bridge/Allocator.sol, contracts/contracts/standard-bridge/L1Gateway.sol, contracts/contracts/standard-bridge/SettlementGateway.sol, contracts/contracts/validator-registry/ValidatorOptInRouter.sol, contracts/contracts/validator-registry/VanillaRegistry.sol, contracts/contracts/validator-registry/avs/MevCommitAVS.sol, contracts/contracts/validator-registry/middleware/MevCommitMiddleware.sol, contracts/scripts/validator-registry/middleware/ReleaseAddrConsts.s.sol
New version of solhint got released (https://github.com/protofire/solhint/releases/tag/v5.1.0) and ci is no longer passing.
So this PR changes order of the functions in our smart contracts
=> fix: fixed solhint

infrastructure/charts/mev-commit-points-service/Chart.yaml, infrastructure/charts/mev-commit-points-service/templates/_helpers.tpl, infrastructure/charts/mev-commit-points-service/templates/configmap.yaml, infrastructure/charts/mev-commit-points-service/templates/deployment.yaml, infrastructure/charts/mev-commit-points-service/templates/ingress.yaml, infrastructure/charts/mev-commit-points-service/templates/pvc.yaml, infrastructure/charts/mev-commit-points-service/templates/service.yaml, infrastructure/charts/mev-commit-points-service/values.yaml
=> feat: add points service chart

contracts/README.md
Updates changelog for provider/bidder registry upgrades
=> chore: update changelog

contracts/contracts/core/BidderRegistry.sol, contracts/contracts/core/BidderRegistryStorage.sol, contracts/contracts/core/ProviderRegistryStorage.sol
While working on the core contracts I've found some unclear and/or misleading comments. This PR updates these comments, and should not change contract functionality in any way.
=> docs: updated comments in core contracts

infrastructure/charts/mev-commit-erigon/Chart.yaml, infrastructure/charts/mev-commit-erigon/templates/_helpers.tpl, infrastructure/charts/mev-commit-erigon/templates/configmap.yaml, infrastructure/charts/mev-commit-erigon/templates/ingress-rpc.yaml, infrastructure/charts/mev-commit-erigon/templates/ingress-ws.yaml, infrastructure/charts/mev-commit-erigon/templates/secret.yaml, infrastructure/charts/mev-commit-erigon/templates/service-erigon.yaml, infrastructure/charts/mev-commit-erigon/templates/service-snode.yaml, infrastructure/charts/mev-commit-erigon/templates/statefulset.yaml, infrastructure/charts/mev-commit-erigon/values.yaml
=> feat: mev commit erigon chart

tools/points-service/main.go
=> fix: fix points svc

cl/blockbuilder/blockbuilder.go, cl/blockbuilder/blockbuilder_test.go, cl/redisapp/leaderfollower/leaderfollower.go
Backports #755 into the `release/v1.2.x` branch
=> feat: simplify single node cl implementation (#755)

tools/dashboard/main.go, tools/dashboard/stathandler.go, x/contracts/events/publisher/ws.go, x/contracts/events/publisher/ws_test.go
Backports https://github.com/primev/mev-commit/pull/774 to the v1.2.x release branch
=> chore: backport pr 774 to release branch

infrastructure/charts/mev-commit-erigon/templates/_helpers-containers.tpl, infrastructure/charts/mev-commit-erigon/templates/_helpers-validations.tpl, infrastructure/charts/mev-commit-erigon/templates/_helpers-volumes.tpl, infrastructure/charts/mev-commit-erigon/templates/statefulset.yaml, infrastructure/charts/mev-commit-erigon/values.yaml, infrastructure/charts/mev-commit-p2p/bootnode-values.yaml, infrastructure/charts/mev-commit-p2p/templates/configmap.yaml, infrastructure/charts/mev-commit-p2p/values-bidder.yaml, infrastructure/charts/mev-commit-p2p/values-provider.yaml, infrastructure/charts/mev-commit-p2p/values.yaml
=> feat: chart changes

contracts-abi/config/mainnet.go, oracle/cmd/main.go, p2p/pkg/node/node.go, tools/bidder-cli/main.go
=> fix: released contracts

tools/preconf-rpc/main.go, tools/preconf-rpc/notifier/notifier.go, tools/preconf-rpc/service/service.go, x/transfer/transfer.go
=> fix: from deployment
